### ISSUE TITLE
getting started diary example not working

### ISSUE THREAD

**Issue by dgreisen** [SpiderOak/crypton#435]
Hello. Trying to get started with crypton. Following the getting started guide. I'm stuck on "running the diary example"

I'm guessing I need to run `crypton-server db:init`; but get error: `no such file or directory, open './server/config/config.development.json'`

Also tried `crypton-server run`, but get error: `password authentication failed for user "crypton_development_user"`

Any assistance is appreciated.

**Comment by daviddahl** [comment]
have you run "make" from the top level?

**Comment by daviddahl** [comment]
and "./check_dependecies.sh" ?

**Comment by dgreisen** [comment]
I was on node v5.5, which isn't supported. Switched back to 4.2.6. Ran make from top level. Server tests pass. One client test fails: 

```
PhantomJS 1.9.8 (Linux 0.0.0) Core default properties should have the correct version FAILED
	AssertionError: expected '0.1.0' to equal '0.0.4'
```

But it is also failing on travis, so not sure that is the problem.

When run integration tests, after all the setup, I get:

```
...
Compiling client code to crypton.js...
Starting Crypton backend...
Running integration tests...
Killing Crypton backend...
```

which suggests that maybe the integration tests aren't running?

after all this, still get the same `no such file or directory, open './server/config/config.development.json'` when running `crypton-server db:init`. But also not sure that's the command I should be running.

Thanks for your help here. I'll make a PR to clarify the getting started guide once this is all working.

**Comment by daviddahl** [comment]
you should probably pull the latest master to clear up the version mismatch

**Comment by dgreisen** [comment]
Just blew away the entire repo, did an npm install in `crypton/server` and a make in `crypton`; got same issue. This looks like more than just a bug in my setup. see https://travis-ci.org/SpiderOak/crypton/builds/106268555#L808

**Comment by daviddahl** [comment]
Whoops. There is a hard-coded value for 0.0.4 in that test. Sorry about that. 

In  order for you to test a crypton app, try the "items" app to see how you store data. 

run 'client/compile.sh --once', then
'cd client/examples/items' and run 'crypton-server'

**Comment by dgreisen** [comment]
np.

It looks like `client/compile.sh --once` does not work because some dependency paths are relative to the directory from which the script is called, rather than the directory of the script itself. If I `cd client && compile.sh --once` it works.

I tried running `crypton-server` from the `client/examples/items` directory and it didn't do anything except  show me the instructions for using `crypton-server`. I again tried `crypton db:init` and I got the same errors as above.

**Comment by dgreisen** [comment]
Ok. After fixing a bunch of little problems (see PRs) I've figured out the big problem. I am on Ubuntu where you must sudo to the postgres user in order to make changes to the databases. It looks like `crypton db:init` only uses username/password, which I'm guessing works fine in OSX? So I am not successfully creating the development user/database/schema. I'm really not sure how to make the db:init work with sudo. I was able to manually create the user/database by modifying the setup_test_environment.sh shell script.

**Comment by dgreisen** [comment]
I'm still not able to run the items example. I'm getting the following error:

```
crypton/client/examples/items$ NODE_ENV=development crypton-server run
2016-02-02T14:14:27.237Z - info: loading datastore
2016-02-02T14:14:27.298Z - info: listening for item updates
2016-02-02T14:14:27.305Z - info: listening for container updates
2016-02-02T14:14:27.344Z - info: starting HTTPS server
2016-02-02T14:14:27.357Z - info: HTTPS server listening on port 1025
2016-02-02T14:14:27.509Z - info: starting socket.io
2016-02-02T14:14:27.531Z - error:  Error: ERROR:  relation "transaction" does not exist
LINE 1:       select * from transaction       where commit_request_t...
                            ^

    at Client._readError (crypton/server/node_modules/pg-native/index.js:80:13)
    at Client._read (crypton/server/node_modules/pg-native/index.js:121:19)
    at emitNone (events.js:67:13)
    at PQ.emit (events.js:166:7)
```

**Comment by daviddahl** [comment]
Oh wow, yeah, your database schema is not complete. Very strange. I am on Ubuntu 15.04 and everything worked for me once I fixed those VERSION strings in the tests. sudo worked for postgres, etc

**Comment by daviddahl** [comment]
What version of postgresql are you running?

**Comment by daviddahl** [comment]
Ok, now I have been able to replicate this error. very strange, investigating...

**Comment by daviddahl** [comment]
2016-02-02T14:47:28.829Z - error: handleError :  [Error: FATAL:  password authentication failed for user "crypton_development_user"
FATAL:  password authentication failed for user "crypton_development_user"
] Error: FATAL:  password authentication failed for user "crypton_development_user"
FATAL:  password authentication failed for user "crypton_development_user"

    at Error (native)

**Comment by dgreisen** [comment]
It might make sense to use the `db:init`/`db:drop` code to setup/tear down your test database, rather than using `setup_test_environment.sh` so that tests fail if that code doesn't work.

**Comment by daviddahl** [comment]
I think all of these errors are due to @grempe's clean up patches. @grempe can you do a completely clean install and try to get a development server running the items example app? My system appears to never create the development postgres db user and nothing can run as no user is authenticated to read or write postgres. This happens on Ubuntu 14 & 15 (04)

**Comment by daviddahl** [comment]
(oh by the way, I did create the development config file by copying and altering the test config file)

**Comment by grempe** [comment]
I think the pull requests from @dgreisen are a good idea.  I did not test them though. I would also suggest keeping the README up to date with that change if it is less strict now where to run them.

I did discover one issue so far in the instructions in that the db:init calls need(ed?) to be run from the top-level repo dir, and not from within server dir as the instructions imply. I'll submit a PR for that. Does the pull request make that work without being in the top-level dir?

You don't have to create the `config.development.json` file. It already exists in the repo in the correct location @ https://github.com/SpiderOak/crypton/tree/master/server/config.  I suspect the pull requests might make this work more flexibly.

I also got the 'FATAL: password authentication failed' error at the `db:init` step.  I looked into that using an Ubuntu 14.04 LTS server with postgres 9.3 and I think I found the root cause, but I am not going to be able to dig into the fix for a while so if you want to attack it this is what I found:

I debugged by adding a `console.log(config.database);` inside server/bin/init.js just inside the `connect()` method. This let me see the connection object that was being passed into connect when the creation of the user was failing on db:init.

What I found was that the initial connection was being made with user 'postgres' but password 'crypton_development_user_password'!!  **This, I believe, is the whole issue with init** and the db failure messages.  If I changed the password in the DB for the postgres user to `crypton_development_user_password` the db:init script worked fine (but don't do that or it will just break when you db:init the test or prod env).

So the problem is that the init script is pulling in the development config from here:

https://github.com/SpiderOak/crypton/blob/5c2a93dc0d6ab346d518dbaa87c6f5e9d7ff5927/server/config/config.development.json#L5

Having the environment specific config files is a big win, you just need to figure out how to use the real postgres username/password when you are bootstrapping the DB with init.  One approach may be to have a And the real postgres user uname/pass should probably be configured in those env specific config files as well and not assumed to have a password of 'postgres' or be empty password.

You'll need to modify init function to use the core postgress uname/pass when setting up the environment specific user account, and then use dev/test/prod env specific accounts for all table creations after that.

Down here in this section may be where you can override the username/pass just for the create user phase. Perhaps there will be two new keys in each env specific file that you use that represent the core postgres user uname/pass:  This would allow a different pg user credential for each env which is definitely what you want.

e.g.

```
{
  "database": {
    "type": "postgres",
    "postgres_user": "postgres",                      <-- NEW KEY
    "postgres_user_password": "postgres",    <-- NEW KEY
    "user": "crypton_development_user",
    "password": "crypton_development_user_password",
    "database": "crypton_development",
    "host": "localhost",
    "port": 5432
  },
```

And use those new keys down here when you are calling createuser:

https://github.com/SpiderOak/crypton/blob/5c2a93dc0d6ab346d518dbaa87c6f5e9d7ff5927/server/bin/init.js#L101

All of this initialization and the Makefiles were in pretty rough shape (totally broken on OS X, and no environment specific config) long before I made any commits and there have recently been commits by others in addition to myself to move it along. Its still a complicated mess but its getting inch-by-inch to where it needs to be...

**Comment by dgreisen** [comment]
> I did discover one issue so far in the instructions in that the db:init calls need(ed?) to be run from the top-level repo dir, and not from within server dir as the instructions imply. I'll submit a PR for that. Does the pull request make that work without being in the top-level dir?

#438  fixes this

> If I changed the password in the DB for the postgres user to crypton_development_user_password the db:init script worked fine (but don't do that or it will just break when you db:init the test or prod env).

Yup. Unfortunately, my understanding is the postgres user in the default  ubuntu install doesn't have _any_ password as a security precaution. The _only_ way to access the postgres user is to `sudo -u postgres`. So it is not simply a matter of changing the password in config. The `db:init` script will have to be modified somehow to use sudo. See https://github.com/SpiderOak/crypton/blob/master/test/bin/setup_test_environment.sh for sudo-aware database setup.

**Comment by grempe** [comment]
See pull request that simplifies and cleans up env specific db:init and db:drop as I outlined above and adds info to the README.

Does not use sudo, and assumes user has setup an appropriate superuser in postgres (e.g. postgres w. empty pass for dev). Feel free to modify for using sudo if you like. IMHO the user should be completely responsible for setting up their postgres users with appropriate permissions.

Enjoy and hope it works well for you.

**Comment by grempe** [comment]
PS : Another argument against using sudo to access the postgres user account is that you are assuming that all other linux environments besides Ubuntu setup a postgres USER account (not DB account) the same way as Ubuntu. I think this is a pretty big assumption and argues for letting the user be responsible for user accounts and not running 'sudo' commands on their system which may be wholly innappropriate.

**Comment by dgreisen** [comment]
Generally agree. I think your PR #440 is a good start. Once the various prs are merged I'll give it another shot. Thanks.  - David
